### ISSUE TITLE
Dependabot auto merge on patch

### ISSUE THREAD

**Issue by Noggling** [equinor/fusion-project-portal#254]
To mitigate dependabot pr we can use  auto merge on patches. this is done in fusion-framework
https://github.com/equinor/fusion-framework/blob/main/.github/workflows/dependabot.yml

```YML
name: Dependabot auto-merge
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
    - name: Dependabot metadata
      id: metadata
      uses: dependabot/fetch-metadata@v1
      with:
        github-token: "${{ github.token }}"
        
    - name: Enable auto-merge for Dependabot PRs
      if: ${{ steps.metadata.outputs.update-type == 'version-update:semver-patch'}}
      run: |
        gh pr review --approve "$PR_URL"
        gh pr merge --auto --squash "$PR_URL"
      env:
        PR_URL: ${{ github.event.pull_request.html_url }}
        GITHUB_TOKEN: ${{ github.token }}

```
